[workspace]

members = [
    "application/kernel",
    "application/gkw_utils",
    "application/ipcp",
    "application/python_integration",
    "application/emg_integration",
    "application/messages",
    "application/watchdog"
]
