[package]
name = "coin_motor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.14.1"
rust_gpiozero = "0.2.0"
gpio = "0.4.1"

[workspace]
