[package]
name = "rust-systems"
version = "0.1.0"
authors = ["rbhagat"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0.2", features = ["full"] }
actix = "0.10.0"
actix-rt = "2.0.2"
#raestro = "0.1.0"
serde_json = "1.0"

# [dependencies.pyo3]
# version = "0.13.1"
# features = ["auto-initialize"]
