[package]
name = "rust-systems"
version = "0.1.0"
authors = ["rbhagat"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]