#!/bin/sh

HEADER='\033[1;36m'
WARNING='\033[1;30m'
CHECKS='\033[1;34m'
SUCCESS='\033[1;32m'
NC='\033[0m' # No Colour

echo "${HEADER}Running checks before pushing to central repository${NC}"
echo "${HEADER}The following checks will be run:\n\t- cargo build\n\t- cargo test${NC}"
echo "${WARNING}Note: if any of these checks fail, this commit will not be pushed; you can skip these checks by pushing with --no-verify, but please use this sparingly${NC}"

echo "${CHECKS}Building rust binary${NC}"
cargo build

echo "${CHECKS}Running tests${NC}"
cargo test

echo "${SUCCESS}Building and testing has successfully finished; pushing to central repo${NC}"
