from ..grip import GripType

OBJECT_GRIP_MAP = {
    "bird": GripType.POWER,
    "cat": GripType.POWER,
    "dog": GripType.POWER,
    "hat": GripType.EXTENSION,
    "backpack": GripType.POWER,
    "umbrella": GripType.POWER,
    "shoe": GripType.TIP,
    "eye glasses": GripType.POWER,
    "handbag": GripType.POWER,
    "tie": GripType.TIP,
    "suitcase": GripType.POWER,
    "frisbee": GripType.EXTENSION,
    "skis": GripType.EXTENSION,
    "snowboard": GripType.EXTENSION,
    "sports ball": GripType.SPHERICAL,
    "kite": GripType.EXTENSION,
    "baseball bat": GripType.POWER,
    "baseball glove": GripType.POWER,
    "skateboard": GripType.EXTENSION,
    "surfboard": GripType.EXTENSION,
    "tennis racket": GripType.POWER,
    "bottle": GripType.POWER,
    "plate": GripType.EXTENSION,
    "wine glass": GripType.POWER,
    "cup": GripType.POWER,
    "fork": GripType.TRIPOD,
    "knife": GripType.POWER,
    "spoon": GripType.TRIPOD,
    "bowl": GripType.EXTENSION,
    "banana": GripType.POWER,
    "apple": GripType.SPHERICAL,
    "sandwich": GripType.EXTENSION,
    "orange": GripType.SPHERICAL,
    "broccoli": GripType.POWER,
    "carrot": GripType.POWER,
    "hot dog": GripType.POWER,
    "pizza": GripType.LATERAL,
    "donut": GripType.POWER,
    "cake": GripType.POWER,
    "chair": GripType.POWER,
    "potted plant": GripType.POWER,
    "mirror": GripType.POWER,
    "window": GripType.POWER,
    "door": GripType.SPHERICAL,
    "laptop": GripType.EXTENSION,
    "mouse": GripType.SPHERICAL,
    "remote": GripType.LATERAL,
    "keyboard": GripType.POWER,
    "cell phone": GripType.POWER,
    "microwave": GripType.POWER,
    "toaster": GripType.POWER,
    "blender": GripType.POWER,
    "book": GripType.POWER,
    "clock": GripType.POWER,
    "vase": GripType.POWER,
    "scissors": GripType.POWER,
    "teddy bear": GripType.POWER,
    "hair drier": GripType.POWER,
    "toothbrush": GripType.POWER,
    "hair brush": GripType.POWER,
}
